### ISSUE TITLE
__PharmacophoreLoadedMol._get_features_atom_ids() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by sherifelsabbagh** [DrrDom/pmapper#10]
I think there is sth wrong with pmapper tool because when I try generate pharmacophore
using Pharmacophore._get_features_atom_ids(mol=mol, smarts_features=smarts)
I found this message "__PharmacophoreLoadedMol._get_features_atom_ids() missing 1 required positional argument: 'self'"

**Comment by DrrDom** [comment]
This works in other way. First, you should create an instance. Second, load a molecule. You may not call directly these functions.

This should work:
```python
p = Pharmacophore()
p._get_features_atom_ids(mol=mol, smarts_features=smarts)
```

**Comment by sherifelsabbagh** [comment]
thanks

it works

**Comment by sherifelsabbagh** [comment]
I think this should also included in the md2pharm.py because the same message appears
