### ISSUE TITLE
Caching documentation typo

### ISSUE THREAD

**Issue by ChemMatt** [DrrDom/pmapper#3]
Hi DrrDom,

Nice work with pmapper, I am looking forward working with it a bit more in the future. I just wanted to point out a typo in the readme.md and documentation. To turn on caching, the P constructor needs the variable "cached" as opposed to "cache", it's super minor but I thought I'd let you know. :)

Best Wishes,
Matt

**Comment by DrrDom** [comment]
Thank you, Matt!
Pavel.
