### ISSUE TITLE
problem about get_features_count()

### ISSUE THREAD

**Issue by XiaoTigerHAO** [DrrDom/pmapper#4]
Hi authors,

Thanks for providing the open source code for getting the pharmacophore signature.

While I found that the 'pharmacophore counts' which obtained with the use of get_features_count() contains only 6 classes: feature_names_dict = {'HBD': 'D', 'HBA': 'A', 'NI': 'N', 'PI': 'P', 'H': 'H', 'AR': 'a'}. I wonder that what's the relationship between those abbreviations and [positive, negative, acceptor, donor, aromatic, sulfur, neutral] ? How can I get all the 8 features?

Thanks for your time and help!

best,
User
March 31, 2022

**Comment by DrrDom** [comment]
I do not fully understand the situation. By default pmapper has 6 types of features: H-donor (D), H-acceptor (A), aromatic (a), H (hydrophobe), N (negative ionizable) and P (positive ionizable). The dict you cited is used to convert LigandScout feature labels to pmapper labels.
What are those 8 features you say about? Are there some new features in LigandScout files which you want to read to pmapper? If so, attach an example of the pharmacophore file containing them and I'll add them or find a workaround.

**Comment by XiaoTigerHAO** [comment]
Thanks for your reply.
Please refer to the paper (mCSM: predicting the effects of mutations in proteins using graph-based signatures, doi: 10.1093/bioinformatics/btt691) for more information. The authors claims that they get the pharmacophore change with the use of Pmapper which results 8 kind of classes for atoms (positive, negative, acceptor, donor, aromatic, sulfur, neutral). The corresponding description can be found on the bottom of Page number 337.
Thanks again!

**Comment by DrrDom** [comment]
I see that the authors mentioned pmapper, but this is somewhat different pmapper. The paper was published in 2014 and this repo was created in 2017. Unfortunately the authors do not provide the reference to pmapper software. I searched and found that Chemaxon has a tool with exactly the same name https://docs.chemaxon.com/display/docs/pharmacophore-perception-pmapper.md. I'm sorry for this collision, I did not aware about it :)

I did not read the paper, so I cannot say whether my pmapper is able to do the same things. If you need structure-based pharmacophore perception then this repo is not suitable. This repo is mainly about creation of pharmacophore representation of individual molecules and manipulation with pharmacophores in general (modification, calculation of descriptors/fingerprints, etc). It also should be taken into account, pmapper does not work with directed features (not implemented), it considers all features as points.
If you'll describe your goals in more details I may suggest how this could be implemented with this pmapper.

**Comment by XiaoTigerHAO** [comment]
Dear author,

I do appreciate your reply and suggestion.
I just want to get the count number of atoms which can be classified to different classes (positive, negative, acceptor, donor, aromatic, sulfur, neutral) in a given molecule (in specific, a part of the protein PDB structure). I guess that your Pmapper can give such count, if I correctly understand the program.

Thanks again!

**Comment by DrrDom** [comment]
If you submit a protein as an RDKit Mol object with correct bind orders, pmapper should work properly in theory (i did not test it on such large molecules). Pmapper will apply SMARTS rules to detect feature types and you may edit these rules and add new ones to represent new feature types if necessary. You may add neutral/sulfur features and edit other as needed. Just a warning, I did not test extensively the program to process new features, so I cannot guarantee proper working of all functions, but simple counting should work.

You can take this file (https://github.com/DrrDom/pmapper/blob/master/pmapper/smarts_features.txt) as a template, edit it and read it by `pmapper.customize.load_smarts` and the output dictionary can be submitted to the function creating pharmacophores from molecules - `load_from_smarts`.

Please note, pmapper does not label each atom, it returns features and their coordinates. So, for a bezene ring it will be one feature in a center of the ring, but if you need information about mapping of individual atoms to pharmacophore features you may retrieve it as well (function `_get_features_atom_ids` in `Pharmacophore` class).

**Comment by XiaoTigerHAO** [comment]
Thanks so much for the intensive description which is turely helpful.
