### ISSUE TITLE
.pma to .xyz format?

### ISSUE THREAD

**Issue by suneelbvs** [DrrDom/pmapper#6]
Hi,

Is it possible to convert .pma to .xyz format using pmapper or psearch?

Please suggest.

Regards,
Suneel

**Comment by DrrDom** [comment]
Of course, there are two functions `load_from_pma` and `save_to_xyz`. So if you have a pharmacophore object `p`, call `p.load_from.pma('file.pma')` and then `p.save_to_xyz('file.xyz')`

**Comment by suneelbvs** [comment]
Thank you @DrrDom. Really helpful.
