### ISSUE TITLE
Extending pmapper functionality to protein residues

### ISSUE THREAD

**Issue by spadavec** [DrrDom/pmapper#7]
Would it be possible to extend this functionality to create pharmacophores for proteins? Specifically, I'm looking to create pharmacophores for protein pockets based on PDB structures alone, and convert those to fingerprints. It appears that the smarts patterns could be modified to those matching protein residues, but the underlying functionality seems to work on a per-atom level, and not a per-object--is that true?

**Comment by DrrDom** [comment]
I did not test that, but it should be possible if a protein is supplied as a mol object with all bond orders. SMARTS patterns maybe can be kept the same, but it is easy to customize them. However, the number of features will be very large and if enumerate quadruplets there will be a combinatorial explosion. Moreover, it avoid many collisions the length of the bit string should be very long. On the other hand, it should be not too difficult to implement calculations of quadruplets if the distance between features do not exceed a given threshold. In this case, quadruplets can be enumerated locally, this will substantially decrease their number.
